version: "3"
services:
  main-service:
    build: ./main-service
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/prepandpost
      - JWT_SECRET=your_jwt_secret
    depends_on:
      - mongo
      - redis
      - kafka

  ats-service:
    build: ./ats-service
    environment:
      - MONGODB_URI=mongodb://mongo:27017/prepandpost
    depends_on:
      - mongo

  coding-service:
    build: ./coding-service
    environment:
      - MONGODB_URI=mongodb://mongo:27017/prepandpost
    depends_on:
      - mongo

  interview-experience-service:
    build: ./interview-experience-service
    environment:
      - MONGODB_URI=mongodb://mongo:27017/prepandpost
    depends_on:
      - mongo

  notification-service:
    build: ./notification-service
    environment:
      - MONGODB_URI=mongodb://mongo:27017/prepandpost
      - KAFKA_HOST=kafka:9092
    depends_on:
      - mongo
      - kafka

  preparation-service:
    build: ./preparation-service
    environment:
      - MONGODB_URI=mongodb://mongo:27017/prepandpost
    depends_on:
      - mongo

  quiz-service:
    build: ./quiz-service
    environment:
      - MONGODB_URI=mongodb://mongo:27017/prepandpost
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  kafka:
    image: wurstmeister/kafka:latest
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper

  zookeeper:
    image: wurstmeister/zookeeper:latest
    ports:
      - "2181:2181"

volumes:
  mongodb_data:
